const githubResult = """
{
"total_count": 27,
"incomplete_results": false,
"items": [
{
"login": "miyahira",
"id": 324801,
"node_id": "MDQ6VXNlcjMyNDgwMQ==",
"avatar_url": "https://avatars.githubusercontent.com/u/324801?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahira",
"html_url": "https://github.com/miyahira",
"followers_url": "https://api.github.com/users/miyahira/followers",
"following_url": "https://api.github.com/users/miyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahira/subscriptions",
"organizations_url": "https://api.github.com/users/miyahira/orgs",
"repos_url": "https://api.github.com/users/miyahira/repos",
"events_url": "https://api.github.com/users/miyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "YoshiiTsuu",
"id": 63078117,
"node_id": "MDQ6VXNlcjYzMDc4MTE3",
"avatar_url": "https://avatars.githubusercontent.com/u/63078117?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/YoshiiTsuu",
"html_url": "https://github.com/YoshiiTsuu",
"followers_url": "https://api.github.com/users/YoshiiTsuu/followers",
"following_url": "https://api.github.com/users/YoshiiTsuu/following{/other_user}",
"gists_url": "https://api.github.com/users/YoshiiTsuu/gists{/gist_id}",
"starred_url": "https://api.github.com/users/YoshiiTsuu/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/YoshiiTsuu/subscriptions",
"organizations_url": "https://api.github.com/users/YoshiiTsuu/orgs",
"repos_url": "https://api.github.com/users/YoshiiTsuu/repos",
"events_url": "https://api.github.com/users/YoshiiTsuu/events{/privacy}",
"received_events_url": "https://api.github.com/users/YoshiiTsuu/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "julioym",
"id": 5834457,
"node_id": "MDQ6VXNlcjU4MzQ0NTc=",
"avatar_url": "https://avatars.githubusercontent.com/u/5834457?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/julioym",
"html_url": "https://github.com/julioym",
"followers_url": "https://api.github.com/users/julioym/followers",
"following_url": "https://api.github.com/users/julioym/following{/other_user}",
"gists_url": "https://api.github.com/users/julioym/gists{/gist_id}",
"starred_url": "https://api.github.com/users/julioym/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/julioym/subscriptions",
"organizations_url": "https://api.github.com/users/julioym/orgs",
"repos_url": "https://api.github.com/users/julioym/repos",
"events_url": "https://api.github.com/users/julioym/events{/privacy}",
"received_events_url": "https://api.github.com/users/julioym/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MiyahiraRyuto",
"id": 73108528,
"node_id": "MDQ6VXNlcjczMTA4NTI4",
"avatar_url": "https://avatars.githubusercontent.com/u/73108528?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MiyahiraRyuto",
"html_url": "https://github.com/MiyahiraRyuto",
"followers_url": "https://api.github.com/users/MiyahiraRyuto/followers",
"following_url": "https://api.github.com/users/MiyahiraRyuto/following{/other_user}",
"gists_url": "https://api.github.com/users/MiyahiraRyuto/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MiyahiraRyuto/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MiyahiraRyuto/subscriptions",
"organizations_url": "https://api.github.com/users/MiyahiraRyuto/orgs",
"repos_url": "https://api.github.com/users/MiyahiraRyuto/repos",
"events_url": "https://api.github.com/users/MiyahiraRyuto/events{/privacy}",
"received_events_url": "https://api.github.com/users/MiyahiraRyuto/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "fmiyahira",
"id": 675320,
"node_id": "MDQ6VXNlcjY3NTMyMA==",
"avatar_url": "https://avatars.githubusercontent.com/u/675320?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/fmiyahira",
"html_url": "https://github.com/fmiyahira",
"followers_url": "https://api.github.com/users/fmiyahira/followers",
"following_url": "https://api.github.com/users/fmiyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/fmiyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/fmiyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/fmiyahira/subscriptions",
"organizations_url": "https://api.github.com/users/fmiyahira/orgs",
"repos_url": "https://api.github.com/users/fmiyahira/repos",
"events_url": "https://api.github.com/users/fmiyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/fmiyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "EduardoMTest",
"id": 75910789,
"node_id": "MDQ6VXNlcjc1OTEwNzg5",
"avatar_url": "https://avatars.githubusercontent.com/u/75910789?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/EduardoMTest",
"html_url": "https://github.com/EduardoMTest",
"followers_url": "https://api.github.com/users/EduardoMTest/followers",
"following_url": "https://api.github.com/users/EduardoMTest/following{/other_user}",
"gists_url": "https://api.github.com/users/EduardoMTest/gists{/gist_id}",
"starred_url": "https://api.github.com/users/EduardoMTest/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/EduardoMTest/subscriptions",
"organizations_url": "https://api.github.com/users/EduardoMTest/orgs",
"repos_url": "https://api.github.com/users/EduardoMTest/repos",
"events_url": "https://api.github.com/users/EduardoMTest/events{/privacy}",
"received_events_url": "https://api.github.com/users/EduardoMTest/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "juliomiyahira",
"id": 838600,
"node_id": "MDQ6VXNlcjgzODYwMA==",
"avatar_url": "https://avatars.githubusercontent.com/u/838600?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/juliomiyahira",
"html_url": "https://github.com/juliomiyahira",
"followers_url": "https://api.github.com/users/juliomiyahira/followers",
"following_url": "https://api.github.com/users/juliomiyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/juliomiyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/juliomiyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/juliomiyahira/subscriptions",
"organizations_url": "https://api.github.com/users/juliomiyahira/orgs",
"repos_url": "https://api.github.com/users/juliomiyahira/repos",
"events_url": "https://api.github.com/users/juliomiyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/juliomiyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusmiyahira",
"id": 46376610,
"node_id": "MDQ6VXNlcjQ2Mzc2NjEw",
"avatar_url": "https://avatars.githubusercontent.com/u/46376610?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusmiyahira",
"html_url": "https://github.com/matheusmiyahira",
"followers_url": "https://api.github.com/users/matheusmiyahira/followers",
"following_url": "https://api.github.com/users/matheusmiyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusmiyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusmiyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusmiyahira/subscriptions",
"organizations_url": "https://api.github.com/users/matheusmiyahira/orgs",
"repos_url": "https://api.github.com/users/matheusmiyahira/repos",
"events_url": "https://api.github.com/users/matheusmiyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusmiyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "andersonmiyahira",
"id": 11889745,
"node_id": "MDQ6VXNlcjExODg5NzQ1",
"avatar_url": "https://avatars.githubusercontent.com/u/11889745?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/andersonmiyahira",
"html_url": "https://github.com/andersonmiyahira",
"followers_url": "https://api.github.com/users/andersonmiyahira/followers",
"following_url": "https://api.github.com/users/andersonmiyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/andersonmiyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/andersonmiyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/andersonmiyahira/subscriptions",
"organizations_url": "https://api.github.com/users/andersonmiyahira/orgs",
"repos_url": "https://api.github.com/users/andersonmiyahira/repos",
"events_url": "https://api.github.com/users/andersonmiyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/andersonmiyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MiyahiraYusuke",
"id": 5052178,
"node_id": "MDQ6VXNlcjUwNTIxNzg=",
"avatar_url": "https://avatars.githubusercontent.com/u/5052178?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MiyahiraYusuke",
"html_url": "https://github.com/MiyahiraYusuke",
"followers_url": "https://api.github.com/users/MiyahiraYusuke/followers",
"following_url": "https://api.github.com/users/MiyahiraYusuke/following{/other_user}",
"gists_url": "https://api.github.com/users/MiyahiraYusuke/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MiyahiraYusuke/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MiyahiraYusuke/subscriptions",
"organizations_url": "https://api.github.com/users/MiyahiraYusuke/orgs",
"repos_url": "https://api.github.com/users/MiyahiraYusuke/repos",
"events_url": "https://api.github.com/users/MiyahiraYusuke/events{/privacy}",
"received_events_url": "https://api.github.com/users/MiyahiraYusuke/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MiyahiraYamato",
"id": 84769368,
"node_id": "MDQ6VXNlcjg0NzY5MzY4",
"avatar_url": "https://avatars.githubusercontent.com/u/84769368?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MiyahiraYamato",
"html_url": "https://github.com/MiyahiraYamato",
"followers_url": "https://api.github.com/users/MiyahiraYamato/followers",
"following_url": "https://api.github.com/users/MiyahiraYamato/following{/other_user}",
"gists_url": "https://api.github.com/users/MiyahiraYamato/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MiyahiraYamato/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MiyahiraYamato/subscriptions",
"organizations_url": "https://api.github.com/users/MiyahiraYamato/orgs",
"repos_url": "https://api.github.com/users/MiyahiraYamato/repos",
"events_url": "https://api.github.com/users/MiyahiraYamato/events{/privacy}",
"received_events_url": "https://api.github.com/users/MiyahiraYamato/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahiraiho",
"id": 48536197,
"node_id": "MDQ6VXNlcjQ4NTM2MTk3",
"avatar_url": "https://avatars.githubusercontent.com/u/48536197?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahiraiho",
"html_url": "https://github.com/miyahiraiho",
"followers_url": "https://api.github.com/users/miyahiraiho/followers",
"following_url": "https://api.github.com/users/miyahiraiho/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahiraiho/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahiraiho/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahiraiho/subscriptions",
"organizations_url": "https://api.github.com/users/miyahiraiho/orgs",
"repos_url": "https://api.github.com/users/miyahiraiho/repos",
"events_url": "https://api.github.com/users/miyahiraiho/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahiraiho/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahira-aym",
"id": 23066036,
"node_id": "MDQ6VXNlcjIzMDY2MDM2",
"avatar_url": "https://avatars.githubusercontent.com/u/23066036?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahira-aym",
"html_url": "https://github.com/miyahira-aym",
"followers_url": "https://api.github.com/users/miyahira-aym/followers",
"following_url": "https://api.github.com/users/miyahira-aym/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahira-aym/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahira-aym/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahira-aym/subscriptions",
"organizations_url": "https://api.github.com/users/miyahira-aym/orgs",
"repos_url": "https://api.github.com/users/miyahira-aym/repos",
"events_url": "https://api.github.com/users/miyahira-aym/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahira-aym/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahira-careritz",
"id": 77036908,
"node_id": "MDQ6VXNlcjc3MDM2OTA4",
"avatar_url": "https://avatars.githubusercontent.com/u/77036908?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahira-careritz",
"html_url": "https://github.com/miyahira-careritz",
"followers_url": "https://api.github.com/users/miyahira-careritz/followers",
"following_url": "https://api.github.com/users/miyahira-careritz/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahira-careritz/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahira-careritz/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahira-careritz/subscriptions",
"organizations_url": "https://api.github.com/users/miyahira-careritz/orgs",
"repos_url": "https://api.github.com/users/miyahira-careritz/repos",
"events_url": "https://api.github.com/users/miyahira-careritz/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahira-careritz/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MIYAHIRA-PG",
"id": 29560656,
"node_id": "MDQ6VXNlcjI5NTYwNjU2",
"avatar_url": "https://avatars.githubusercontent.com/u/29560656?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MIYAHIRA-PG",
"html_url": "https://github.com/MIYAHIRA-PG",
"followers_url": "https://api.github.com/users/MIYAHIRA-PG/followers",
"following_url": "https://api.github.com/users/MIYAHIRA-PG/following{/other_user}",
"gists_url": "https://api.github.com/users/MIYAHIRA-PG/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MIYAHIRA-PG/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MIYAHIRA-PG/subscriptions",
"organizations_url": "https://api.github.com/users/MIYAHIRA-PG/orgs",
"repos_url": "https://api.github.com/users/MIYAHIRA-PG/repos",
"events_url": "https://api.github.com/users/MIYAHIRA-PG/events{/privacy}",
"received_events_url": "https://api.github.com/users/MIYAHIRA-PG/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahira1",
"id": 51349916,
"node_id": "MDQ6VXNlcjUxMzQ5OTE2",
"avatar_url": "https://avatars.githubusercontent.com/u/51349916?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahira1",
"html_url": "https://github.com/miyahira1",
"followers_url": "https://api.github.com/users/miyahira1/followers",
"following_url": "https://api.github.com/users/miyahira1/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahira1/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahira1/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahira1/subscriptions",
"organizations_url": "https://api.github.com/users/miyahira1/orgs",
"repos_url": "https://api.github.com/users/miyahira1/repos",
"events_url": "https://api.github.com/users/miyahira1/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahira1/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahira-albert-lvgs",
"id": 60081002,
"node_id": "MDQ6VXNlcjYwMDgxMDAy",
"avatar_url": "https://avatars.githubusercontent.com/u/60081002?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahira-albert-lvgs",
"html_url": "https://github.com/miyahira-albert-lvgs",
"followers_url": "https://api.github.com/users/miyahira-albert-lvgs/followers",
"following_url": "https://api.github.com/users/miyahira-albert-lvgs/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahira-albert-lvgs/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahira-albert-lvgs/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahira-albert-lvgs/subscriptions",
"organizations_url": "https://api.github.com/users/miyahira-albert-lvgs/orgs",
"repos_url": "https://api.github.com/users/miyahira-albert-lvgs/repos",
"events_url": "https://api.github.com/users/miyahira-albert-lvgs/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahira-albert-lvgs/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "h-miyahira",
"id": 29747068,
"node_id": "MDQ6VXNlcjI5NzQ3MDY4",
"avatar_url": "https://avatars.githubusercontent.com/u/29747068?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/h-miyahira",
"html_url": "https://github.com/h-miyahira",
"followers_url": "https://api.github.com/users/h-miyahira/followers",
"following_url": "https://api.github.com/users/h-miyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/h-miyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/h-miyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/h-miyahira/subscriptions",
"organizations_url": "https://api.github.com/users/h-miyahira/orgs",
"repos_url": "https://api.github.com/users/h-miyahira/repos",
"events_url": "https://api.github.com/users/h-miyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/h-miyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahirasharon",
"id": 54814801,
"node_id": "MDQ6VXNlcjU0ODE0ODAx",
"avatar_url": "https://avatars.githubusercontent.com/u/54814801?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahirasharon",
"html_url": "https://github.com/miyahirasharon",
"followers_url": "https://api.github.com/users/miyahirasharon/followers",
"following_url": "https://api.github.com/users/miyahirasharon/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahirasharon/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahirasharon/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahirasharon/subscriptions",
"organizations_url": "https://api.github.com/users/miyahirasharon/orgs",
"repos_url": "https://api.github.com/users/miyahirasharon/repos",
"events_url": "https://api.github.com/users/miyahirasharon/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahirasharon/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahirashotaro",
"id": 63690884,
"node_id": "MDQ6VXNlcjYzNjkwODg0",
"avatar_url": "https://avatars.githubusercontent.com/u/63690884?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahirashotaro",
"html_url": "https://github.com/miyahirashotaro",
"followers_url": "https://api.github.com/users/miyahirashotaro/followers",
"following_url": "https://api.github.com/users/miyahirashotaro/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahirashotaro/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahirashotaro/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahirashotaro/subscriptions",
"organizations_url": "https://api.github.com/users/miyahirashotaro/orgs",
"repos_url": "https://api.github.com/users/miyahirashotaro/repos",
"events_url": "https://api.github.com/users/miyahirashotaro/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahirashotaro/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahira-A",
"id": 75720507,
"node_id": "MDQ6VXNlcjc1NzIwNTA3",
"avatar_url": "https://avatars.githubusercontent.com/u/75720507?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahira-A",
"html_url": "https://github.com/miyahira-A",
"followers_url": "https://api.github.com/users/miyahira-A/followers",
"following_url": "https://api.github.com/users/miyahira-A/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahira-A/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahira-A/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahira-A/subscriptions",
"organizations_url": "https://api.github.com/users/miyahira-A/orgs",
"repos_url": "https://api.github.com/users/miyahira-A/repos",
"events_url": "https://api.github.com/users/miyahira-A/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahira-A/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahira0902",
"id": 19884510,
"node_id": "MDQ6VXNlcjE5ODg0NTEw",
"avatar_url": "https://avatars.githubusercontent.com/u/19884510?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahira0902",
"html_url": "https://github.com/miyahira0902",
"followers_url": "https://api.github.com/users/miyahira0902/followers",
"following_url": "https://api.github.com/users/miyahira0902/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahira0902/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahira0902/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahira0902/subscriptions",
"organizations_url": "https://api.github.com/users/miyahira0902/orgs",
"repos_url": "https://api.github.com/users/miyahira0902/repos",
"events_url": "https://api.github.com/users/miyahira0902/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahira0902/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "miyahira-temperance",
"id": 81783665,
"node_id": "MDQ6VXNlcjgxNzgzNjY1",
"avatar_url": "https://avatars.githubusercontent.com/u/81783665?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/miyahira-temperance",
"html_url": "https://github.com/miyahira-temperance",
"followers_url": "https://api.github.com/users/miyahira-temperance/followers",
"following_url": "https://api.github.com/users/miyahira-temperance/following{/other_user}",
"gists_url": "https://api.github.com/users/miyahira-temperance/gists{/gist_id}",
"starred_url": "https://api.github.com/users/miyahira-temperance/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/miyahira-temperance/subscriptions",
"organizations_url": "https://api.github.com/users/miyahira-temperance/orgs",
"repos_url": "https://api.github.com/users/miyahira-temperance/repos",
"events_url": "https://api.github.com/users/miyahira-temperance/events{/privacy}",
"received_events_url": "https://api.github.com/users/miyahira-temperance/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "alessandroMiyahira",
"id": 65517979,
"node_id": "MDQ6VXNlcjY1NTE3OTc5",
"avatar_url": "https://avatars.githubusercontent.com/u/65517979?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/alessandroMiyahira",
"html_url": "https://github.com/alessandroMiyahira",
"followers_url": "https://api.github.com/users/alessandroMiyahira/followers",
"following_url": "https://api.github.com/users/alessandroMiyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/alessandroMiyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/alessandroMiyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/alessandroMiyahira/subscriptions",
"organizations_url": "https://api.github.com/users/alessandroMiyahira/orgs",
"repos_url": "https://api.github.com/users/alessandroMiyahira/repos",
"events_url": "https://api.github.com/users/alessandroMiyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/alessandroMiyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "103iho",
"id": 49139002,
"node_id": "MDQ6VXNlcjQ5MTM5MDAy",
"avatar_url": "https://avatars.githubusercontent.com/u/49139002?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/103iho",
"html_url": "https://github.com/103iho",
"followers_url": "https://api.github.com/users/103iho/followers",
"following_url": "https://api.github.com/users/103iho/following{/other_user}",
"gists_url": "https://api.github.com/users/103iho/gists{/gist_id}",
"starred_url": "https://api.github.com/users/103iho/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/103iho/subscriptions",
"organizations_url": "https://api.github.com/users/103iho/orgs",
"repos_url": "https://api.github.com/users/103iho/repos",
"events_url": "https://api.github.com/users/103iho/events{/privacy}",
"received_events_url": "https://api.github.com/users/103iho/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "emiyahira",
"id": 41088776,
"node_id": "MDQ6VXNlcjQxMDg4Nzc2",
"avatar_url": "https://avatars.githubusercontent.com/u/41088776?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/emiyahira",
"html_url": "https://github.com/emiyahira",
"followers_url": "https://api.github.com/users/emiyahira/followers",
"following_url": "https://api.github.com/users/emiyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/emiyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/emiyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/emiyahira/subscriptions",
"organizations_url": "https://api.github.com/users/emiyahira/orgs",
"repos_url": "https://api.github.com/users/emiyahira/repos",
"events_url": "https://api.github.com/users/emiyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/emiyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "gabrielmiyahira",
"id": 18669179,
"node_id": "MDQ6VXNlcjE4NjY5MTc5",
"avatar_url": "https://avatars.githubusercontent.com/u/18669179?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/gabrielmiyahira",
"html_url": "https://github.com/gabrielmiyahira",
"followers_url": "https://api.github.com/users/gabrielmiyahira/followers",
"following_url": "https://api.github.com/users/gabrielmiyahira/following{/other_user}",
"gists_url": "https://api.github.com/users/gabrielmiyahira/gists{/gist_id}",
"starred_url": "https://api.github.com/users/gabrielmiyahira/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/gabrielmiyahira/subscriptions",
"organizations_url": "https://api.github.com/users/gabrielmiyahira/orgs",
"repos_url": "https://api.github.com/users/gabrielmiyahira/repos",
"events_url": "https://api.github.com/users/gabrielmiyahira/events{/privacy}",
"received_events_url": "https://api.github.com/users/gabrielmiyahira/received_events",
"type": "User",
"site_admin": false,
"score": 1
}
]
}
""";
